package br.unb.cic.js.walker;

import br.unb.cic.js.date.Interval;
import lombok.Builder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Path;

@Builder
public class RepositoryWalkerTask implements Runnable {
    private final Logger logger = LoggerFactory.getLogger(getClass());

    // The report is the csv file generated by the program after all observations of a given project are finished.
    public final Path report;

    public final RepositoryWalker walker;

    public final Interval interval;

    public final int steps;

    @Override
    public void run() {
        try {
            walker.traverse(interval.begin, interval.end, steps);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
